In [1]:
import pandas as pd
from pathlib import Path

In [2]:
df = pd.read_csv('faculty20-21.csv')
df.drop("Unnamed: 0", inplace=True, axis=1)

In [5]:
df

,name,title,degrees,leave
0,Daniel P. Aalberts,Kennedy P. Richardson '71 Professor of Physics,"1989, B.S., Massachusetts Institute of Technol...",n
1,Tomas Adalsteinsson,Assistant Professor of Physical Education and ...,"2011, M.A., John F. Kennedy University",n
2,Colin C. Adams,Thomas T. Read Professor of Mathematics,"1978, B.S., Massachusetts Institute of Technol...",y
3,Zaid Adhami,Assistant Professor of Religion and Faculty Af...,"2010, M.A., Stanford University, 2010, B.A., S...",f
4,Jeannie R Albrecht,Professor of Computer Science,"2001, B.S., Gettysburg College, 2003, M.S., Du...",y
...,...,...,...,...
430,Safa R. Zaki,"Dean of the Faculty, Professor of Psychology","1989, B.A., American University, 1993, M.A., A...",n
431,Liya Zalaltdinova,Visiting Lecturer in Russian,"2019, Ph.D., State University of New York at A...",n
432,Sofia E. Zepeda,Assistant Professor at Williams-Mystic,"2008, B.A., University of California, Santa Cr...",n
433,David J. Zimmerman,Professor of Economics and Orrin Sage Professo...,"1985, B.A., University of Toronto, 1987, M.A.,...",s
434,Charles U. Zug,Visiting Assistant Professor of Leadership Stu...,"2015, B.A., St. John's College, 2017, M.A., Un...",n